# Loaded at runtime.

import Config

web_port = String.to_integer(System.get_env("XOMIUM_WEB_PORT") || "4000")

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :xomium_web, XomiumWeb.Endpoint,
  url: [host: "xomium.com", port: web_port],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :xomium_web, XomiumWeb.Endpoint,
  http: [
    port: web_port,
    transport_options: [socket_opts: [:inet6]]
  ]

# database_url =
#   System.get_env("DATABASE_URL") ||
#     raise """
#     environment variable DATABASE_URL is missing.
#     For example: ecto://USER:PASS@HOST/DATABASE
#     """

# config :xomium, Xomium.Repo,
#   # ssl: true,
#   url: database_url,
#   pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

secret_key_base =
  System.get_env("XOMIUM_SECRET_KEY_BASE") ||
    raise """
    environment variable XOMIUM_SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :xomium_web, XomiumWeb.Endpoint, secret_key_base: secret_key_base
